title: MattShwery.com
auto: true
permalink: /:title
paginate: 10
exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_css: style
    coderay_line_numbers: nil
